services:
  litellm-proxy:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm-proxy
    ports:
      - "8000:8000"
    environment:
      - LITELLM_MASTER_KEY=sk-1234567890abcdef
    volumes:
      - ./config.yaml:/app/config.yaml
    command: >
      --config /app/config.yaml
      --port 8000
    restart: unless-stopped
    networks:
      - ollama_default

networks:
  ollama_default:
    external: true
