version: '3'
services:
  litellm-proxy:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm-proxy
    ports:
      - "8000:8000"
    environment:
      - LITELLM_MASTER_KEY=sk-1234567890abcdef
      - LITELLM_SALT_KEY=sk-salt-key-litellm-proxy
      - STORE_MODEL_IN_DB="False"
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/litellm
    volumes:
      - ./config.yaml:/app/config.yaml
    command: >
      --config /app/config.yaml
      --port 8000
    restart: unless-stopped
    networks:
      - ollama_default
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: litellm-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=litellm
    networks:
      - ollama_default

networks:
  ollama_default:
    external: true
